CCS-14: Create Route Handler for Delete Functionality
CornerCaseSolutions/ccs-inventory-management-api pull request #6
Opened 2024-06-20 15:57 UTC by jmusone

Added delete clothing handler.

2024-06-20 20:17 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/route/DeleteClothingHandler.java
> +                .flatMap(new Function<UpdateClothingHandler.Request, Mono<? extends Clothing>>() {
You don't need a cast here, you can use a lambda.

2024-06-20 20:17 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/route/DeleteClothingHandler.java
> +                }).flatMap(new Function<Clothing, Mono<? extends ServerResponse>>() {
Same here

2024-06-20 20:18 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/route/DeleteClothingHandler.java
> +                .onErrorResume(ex -> ServerResponse.badRequest().build());
Bad request, or 4xx errors are typically used for client side problems and suggests the client to modify their request.
If the problem is coming internally, these should be 5xx style errors.

2024-06-20 20:20 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/service/ClothingService.java
> +                .map(Clothing::from);
A delete call should not be passing you an entity to save, you should just receive the ID of the entity requesting to be removed and then looking it up, and if it exists, perform your delete logic.

2024-06-20 20:20 UTC, hitchan requested changes
Please review the comments and let me know what you think

2024-06-21 19:01 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/repo/ClothingRepository.java
> +    Mono<Void> deleteByID(UUID id);
You may want to rename this method to let callers know what it really does. Something like "softDelete()" or something like that. 99.9% of the time "delete" in a repo means to remove the row completely. You could even make an update method that takes the enum so you could implement undo operations.

2024-06-21 19:02 UTC, hitchan requested changes

2024-06-21 19:02 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/route/DeleteClothingHandler.java
> +                .flatMap((Function<UpdateClothingHandler.Request, Mono<? extends Clothing>>) request -> service.update(Clothing.builder()
Remove the cast, it is not required.

2024-06-21 19:02 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/route/DeleteClothingHandler.java
> +                        .build())).flatMap((Function<Clothing, Mono<? extends ServerResponse>>) clothing -> ServerResponse.ok()
Same here

2024-06-22 01:08 UTC, hitchan commented on InventoryManagement/src/main/java/com/ccs/inventorymanagement/repo/ClothingRepository.java
> +    @Query("UPDATE clothing SET status = 'ISSUED' WHERE id = $0")
Does ISSUED mean deleted in this system?

2024-06-22 13:25 UTC, hitchan approved these changes

2024-06-24 15:57 UTC, RRDarius approved these changes

2024-06-26 02:46 UTC, merged